site_name: LODKit Docs

theme:
  name: "material"

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true

nav:
  - index.md
  - reference.md
  - tutorials.md
